config/routes.rb
Rails.application.routes.draw do
  resources :tik_tok_posts
  resources :posts

  # Defines the root path route ("/") ---- example.com
  root "articles#index"

  resources :articles 

  # Easter Egg
  get '/teapot', to: 'application#teapot'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/tik_tok_post.rb
class TikTokPost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def teapot
        render plain: "I'm a teapot", status: 418
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show 
    @article = Article.find(params[:id]) # check the URL for something like example.com/article/3
  end

  def new
    @article = Article.new
  end

  def create 
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to @article # redirects to example.com/article/1
    else
      render :new, status: :unprocessable_entity # shows you the form so you can try again
    end
  end


  private
    def article_params
      params.require(:article).permit(:title, :body)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/tik_tok_posts_controller.rb
class TikTokPostsController < ApplicationController
  before_action :set_tik_tok_post, only: %i[ show edit update destroy ]

  # GET /tik_tok_posts or /tik_tok_posts.json
  def index
    @tik_tok_posts = TikTokPost.all
  end

  # GET /tik_tok_posts/1 or /tik_tok_posts/1.json
  def show
  end

  # GET /tik_tok_posts/new
  def new
    @tik_tok_post = TikTokPost.new
  end

  # GET /tik_tok_posts/1/edit
  def edit
  end

  # POST /tik_tok_posts or /tik_tok_posts.json
  def create
    @tik_tok_post = TikTokPost.new(tik_tok_post_params)

    respond_to do |format|
      if @tik_tok_post.save
        format.html { redirect_to tik_tok_post_url(@tik_tok_post), notice: "Tik tok post was successfully created." }
        format.json { render :show, status: :created, location: @tik_tok_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tik_tok_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tik_tok_posts/1 or /tik_tok_posts/1.json
  def update
    respond_to do |format|
      if @tik_tok_post.update(tik_tok_post_params)
        format.html { redirect_to tik_tok_post_url(@tik_tok_post), notice: "Tik tok post was successfully updated." }
        format.json { render :show, status: :ok, location: @tik_tok_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tik_tok_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tik_tok_posts/1 or /tik_tok_posts/1.json
  def destroy
    @tik_tok_post.destroy!

    respond_to do |format|
      format.html { redirect_to tik_tok_posts_url, notice: "Tik tok post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tik_tok_post
      @tik_tok_post = TikTokPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tik_tok_post_params
      params.require(:tik_tok_post).permit(:caption, :author, :views, :likes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tik_tok_posts_helper.rb
module TikTokPostsHelper
end

app/views/articles/index.html.erb
<h1>Articles</h1>

<p>Here are all your articles:</p>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_with model: @article do |form| %>

    <div>
        <%= form.label :title %> <br>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :body %> <br>
        <%= form.text_field :body %>
    </div>
    
    <div>
        <%= form.submit %>
    </div>

<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <h1>
    <%= post.title %>
  </h1>

  <p>
    <%= post.body %>
  </p>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/tik_tok_posts/_form.html.erb
<%= form_with(model: tik_tok_post) do |form| %>
  <% if tik_tok_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tik_tok_post.errors.count, "error") %> prohibited this tik_tok_post from being saved:</h2>

      <ul>
        <% tik_tok_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :caption, style: "display: block" %>
    <%= form.text_area :caption %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :views, style: "display: block" %>
    <%= form.number_field :views %>
  </div>

  <div>
    <%= form.label :likes, style: "display: block" %>
    <%= form.number_field :likes %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tik_tok_posts/_tik_tok_post.html.erb
<div id="<%= dom_id tik_tok_post %>">
  <p>
    <strong>Caption:</strong>
    <%= tik_tok_post.caption %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= tik_tok_post.author %>
  </p>

  <p>
    <strong>Views:</strong>
    <%= tik_tok_post.views %>
  </p>

  <p>
    <strong>Likes:</strong>
    <%= tik_tok_post.likes %>
  </p>

</div>

app/views/tik_tok_posts/edit.html.erb
<h1>Editing tik tok post</h1>

<%= render "form", tik_tok_post: @tik_tok_post %>

<br>

<div>
  <%= link_to "Show this tik tok post", @tik_tok_post %> |
  <%= link_to "Back to tik tok posts", tik_tok_posts_path %>
</div>

app/views/tik_tok_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tik tok posts</h1>

<div id="tik_tok_posts">
  <% @tik_tok_posts.each do |tik_tok_post| %>
    <%= render tik_tok_post %>
    <p>
      <%= link_to "Show this tik tok post", tik_tok_post %>
    </p>
  <% end %>
</div>

<%= link_to "New tik tok post", new_tik_tok_post_path %>

app/views/tik_tok_posts/new.html.erb
<h1>New tik tok post</h1>

<%= render "form", tik_tok_post: @tik_tok_post %>

<br>

<div>
  <%= link_to "Back to tik tok posts", tik_tok_posts_path %>
</div>

app/views/tik_tok_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tik_tok_post %>

<div>
  <%= link_to "Edit this tik tok post", edit_tik_tok_post_path(@tik_tok_post) %> |
  <%= link_to "Back to tik tok posts", tik_tok_posts_path %>

  <%= button_to "Destroy this tik tok post", @tik_tok_post, method: :delete %>
</div>